### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by Segran** [bdraco/ismartgate#1]
## Description
The Ismartgate integration stopped working (didn't load) after upgrading Home Assistant to ver. 2021.7. I then removed the Ismartgate integration and tried to add it again. This do not work as I get Error! Config flow could not be loaded.

I then deleted all files/directories that contained gogogate2 and Ismartgate, uninstalled the 2021.7 distribution and re-installed Home Assistant, but nothing I do have made any difference.

## Expected Behavior
I expected Ismartgate installation to begin so I could enter the ip-adress, user and password and finalize the installation.

## Reproduction
2021-07-21 00:04:23 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration gogogate2: cannot import name 'Loopback' from partially initialized module 'scapy.layers.l2' (most likely due to a circular import) (/Users/MiniMac/homeassistant/lib/python3.9/site-packages/scapy/layers/l2.py)

## Environment
I'm running Mac OS Catalina with Home Assistant in a virtual environment using pyenv version 3.9.4.

**Comment by bdraco** [comment]
Please open an issue here https://github.com/home-assistant/core/issues as this repo is only for specific problems with the ismartgate library itself.

Thanks 👍
